languages:
  - ubuntu

variables:
  - key: value

phases:
  pre:
    - echo "Pre phase"
    - ps -a

  test:
    - echo "Test phase"

  build:
    - echo "Build phase"

  post:
    - echo "Post phase"

  deploy:
    - echo "Deploy phase"
