languages:
  - phpunit

variables:
  - key: value
  - key: value

phases:
  pre:
    messages:
      success: Yay! Tests passed!
    commands:
      - composer install

  test:
    commands:
      - ./vendor/bin/phpunit

  build:
    commands:
      - echo "Build phase"

  post:
    commands:
      - echo "Post phase"

  deploy:
    commands:
      - echo "Deploy phase"
