languages:
  - phpunit

variables:
  - key: value
  - key: value

phases:
  pre:
    description: This is where installing packages happens.
    target_url: https://www.google.com
    commands:
      - composer install

  test:
    description: This is where tests run
    commands:
      - ./vendor/bin/phpunit
      - false

  build:
    commands:
      - echo "Build phase"

  post:
    commands:
      - echo "Post phase"

  deploy:
    commands:
      - echo "Deploy phase"
