languages:
  - phpunit

variables:
  - key: value
  - key: value

phases:
  pre:
    - composer install

  test:
    - ./vendor/bin/phpunit

  build:
    - echo "Build phase"

  post:
    - echo "Post phase"

  deploy:
    - echo "Deploy phase"
