languages:
  - ubuntu

variables:
  - key: value

phases:
  pre:
    - command: echo "Pre phase"

  test:
    - command: echo "Test phase"

  build:
    - command: echo "Build phase"

  post:
    - command: echo "Post phase"

  deploy:
    - command: echo "Deploy phase"
