web:
  image: dydx/alpine-nginx-phpfpm
  ports:
    - "8000:8000"
  expose:
    - "8000"
  volumes:
    - .:/var/www
    - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
  environment:
    TERM: xterm
    APP_ENV: local
    XDEBUG_CONFIG: idekey=PHPSTORM
    PHP_IDE_CONFIG: serverName=docker.cli
    VIRTUAL_HOST: laravel.dev
    VIRTUAL_PORT: 8000
  # external_links:
  #   - mysql:mysql
